In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://github.com/mishravipul/data/raw/main/simple_linear_data.csv")

In [3]:
df.insert(0 , "bias" , 1) 

In [4]:
df.head()

bias  G2  G3
0     1  30  30
1     1  25  30
2     1  40  50
3     1  70  75
4     1  50  50

In [5]:
X = df[["bias" , "G2"]].values
y = df["G3"].values

In [6]:
def hypothesis(X , wieght):
    return X @ wieght

In [7]:
XT = X.T
w = np.linalg.inv(XT @ X) @XT @ y

In [8]:
def MSE(y , hypothesis):
    mse = np.mean(np.square(y - hypothesis))
    return mse

In [9]:
MSE(y , hypothesis(X , w))

np.float64(94.84953286110661)

In [10]:
def gradient(X , hypothesis , y):
    n = len(y)
    gradient = (X.T @ (hypothesis - y))/n
    return gradient
    

In [11]:
gradient(X , hypothesis(X , w) , y)

array([-2.41224762e-14, -1.96721401e-12])

In [12]:
def gradient_descent(X , y , w , alpha):
    for _ in range(1000):
        G = gradient(X , hypothesis(X , w) , y)
        w = w - alpha*G

    return w


In [13]:
gradient_descent(X , y , w , alpha=0.00001)

array([-6.96379103,  1.10211236])

In [14]:
#removing outlier

mean = df["G3"].mean()
std = df["G3"].std()

data_clean = df[(df["G3"] >= mean - 2*std) & (df["G3"] <= mean + 2*std)]

In [15]:
X_clean = data_clean[["bias" , "G2"]].values
y_clean = data_clean["G3"].values

In [16]:
X_cleanT = X_clean.T
w_clean = np.linalg.inv(X_cleanT @ X_clean) @ X_cleanT @ y_clean

In [17]:
MSE(y_clean , hypothesis(X_clean , w_clean))

np.float64(17.561541540397553)

In [18]:
gradient(X_clean , hypothesis(X_clean , w_clean) , y_clean)

array([4.94984827e-15, 2.36315337e-14])

In [19]:
gradient_descent(X_clean , y_clean , w_clean , alpha=0.00001)

array([1.4775025, 0.9883057])

In [20]:
new_w = np.random.rand(2)
new_w= np.zeros(2)


In [21]:
MSE(y, hypothesis(X , new_w))

np.float64(3235.3164556962024)

In [22]:
gradient(X , hypothesis(X , new_w) , y)

array([  -52.07594937, -3178.5443038 ])

In [23]:
gradient_descent(X , y , new_w , alpha=0.00001)

array([0.00875636, 0.98620057])